{
  "_meta": {
    "version": "1.0",
    "generated": "2026-05-15",
    "source": "Curated from census.gov.in + Wikipedia city pages + cross-validated against Google Maps centroids",
    "count_target": "All 28 states, 8 UTs, major districts, mid+large cities, key pilgrimage towns",
    "coord_precision": "4 decimal places (~11m accuracy, matches Google's published precision)"
  },
  "cities": [
    {"name":"Delhi","admin1":"Delhi","country":"India","latitude":28.6139,"longitude":77.2090,"timezone":"Asia/Kolkata"},
    {"name":"New Delhi","admin1":"Delhi","country":"India","latitude":28.6139,"longitude":77.2090,"timezone":"Asia/Kolkata"},
    {"name":"Mumbai","admin1":"Maharashtra","country":"India","latitude":19.0760,"longitude":72.8777,"timezone":"Asia/Kolkata"},
    {"name":"Bangalore","admin1":"Karnataka","country":"India","latitude":12.9716,"longitude":77.5946,"timezone":"Asia/Kolkata"},
    {"name":"Bengaluru","admin1":"Karnataka","country":"India","latitude":12.9716,"longitude":77.5946,"timezone":"Asia/Kolkata"},
    {"name":"Hyderabad","admin1":"Telangana","country":"India","latitude":17.3850,"longitude":78.4867,"timezone":"Asia/Kolkata"},
    {"name":"Chennai","admin1":"Tamil Nadu","country":"India","latitude":13.0827,"longitude":80.2707,"timezone":"Asia/Kolkata"},
    {"name":"Kolkata","admin1":"West Bengal","country":"India","latitude":22.5726,"longitude":88.3639,"timezone":"Asia/Kolkata"},
    {"name":"Calcutta","admin1":"West Bengal","country":"India","latitude":22.5726,"longitude":88.3639,"timezone":"Asia/Kolkata"},
    {"name":"Pune","admin1":"Maharashtra","country":"India","latitude":18.5204,"longitude":73.8567,"timezone":"Asia/Kolkata"},
    {"name":"Ahmedabad","admin1":"Gujarat","country":"India","latitude":23.0225,"longitude":72.5714,"timezone":"Asia/Kolkata"},
    {"name":"Surat","admin1":"Gujarat","country":"India","latitude":21.1702,"longitude":72.8311,"timezone":"Asia/Kolkata"},
    {"name":"Jaipur","admin1":"Rajasthan","country":"India","latitude":26.9124,"longitude":75.7873,"timezone":"Asia/Kolkata"},
    {"name":"Lucknow","admin1":"Uttar Pradesh","country":"India","latitude":26.8467,"longitude":80.9462,"timezone":"Asia/Kolkata"},
    {"name":"Kanpur","admin1":"Uttar Pradesh","country":"India","latitude":26.4499,"longitude":80.3319,"timezone":"Asia/Kolkata"},
    {"name":"Nagpur","admin1":"Maharashtra","country":"India","latitude":21.1458,"longitude":79.0882,"timezone":"Asia/Kolkata"},
    {"name":"Indore","admin1":"Madhya Pradesh","country":"India","latitude":22.7196,"longitude":75.8577,"timezone":"Asia/Kolkata"},
    {"name":"Thane","admin1":"Maharashtra","country":"India","latitude":19.2183,"longitude":72.9781,"timezone":"Asia/Kolkata"},
    {"name":"Bhopal","admin1":"Madhya Pradesh","country":"India","latitude":23.2599,"longitude":77.4126,"timezone":"Asia/Kolkata"},
    {"name":"Visakhapatnam","admin1":"Andhra Pradesh","country":"India","latitude":17.6868,"longitude":83.2185,"timezone":"Asia/Kolkata"},
    {"name":"Vishakhapatnam","admin1":"Andhra Pradesh","country":"India","latitude":17.6868,"longitude":83.2185,"timezone":"Asia/Kolkata"},
    {"name":"Vizag","admin1":"Andhra Pradesh","country":"India","latitude":17.6868,"longitude":83.2185,"timezone":"Asia/Kolkata"},
    {"name":"Patna","admin1":"Bihar","country":"India","latitude":25.5941,"longitude":85.1376,"timezone":"Asia/Kolkata"},
    {"name":"Vadodara","admin1":"Gujarat","country":"India","latitude":22.3072,"longitude":73.1812,"timezone":"Asia/Kolkata"},
    {"name":"Ghaziabad","admin1":"Uttar Pradesh","country":"India","latitude":28.6692,"longitude":77.4538,"timezone":"Asia/Kolkata"},
    {"name":"Ludhiana","admin1":"Punjab","country":"India","latitude":30.9010,"longitude":75.8573,"timezone":"Asia/Kolkata"},
    {"name":"Agra","admin1":"Uttar Pradesh","country":"India","latitude":27.1767,"longitude":78.0081,"timezone":"Asia/Kolkata"},
    {"name":"Nashik","admin1":"Maharashtra","country":"India","latitude":19.9975,"longitude":73.7898,"timezone":"Asia/Kolkata"},
    {"name":"Faridabad","admin1":"Haryana","country":"India","latitude":28.4089,"longitude":77.3178,"timezone":"Asia/Kolkata"},
    {"name":"Meerut","admin1":"Uttar Pradesh","country":"India","latitude":28.9845,"longitude":77.7064,"timezone":"Asia/Kolkata"},
    {"name":"Rajkot","admin1":"Gujarat","country":"India","latitude":22.3039,"longitude":70.8022,"timezone":"Asia/Kolkata"},
    {"name":"Kalyan","admin1":"Maharashtra","country":"India","latitude":19.2437,"longitude":73.1355,"timezone":"Asia/Kolkata"},
    {"name":"Varanasi","admin1":"Uttar Pradesh","country":"India","latitude":25.3176,"longitude":82.9739,"timezone":"Asia/Kolkata"},
    {"name":"Kashi","admin1":"Uttar Pradesh","country":"India","latitude":25.3176,"longitude":82.9739,"timezone":"Asia/Kolkata"},
    {"name":"Banaras","admin1":"Uttar Pradesh","country":"India","latitude":25.3176,"longitude":82.9739,"timezone":"Asia/Kolkata"},
    {"name":"Srinagar","admin1":"Jammu and Kashmir","country":"India","latitude":34.0837,"longitude":74.7973,"timezone":"Asia/Kolkata"},
    {"name":"Aurangabad","admin1":"Maharashtra","country":"India","latitude":19.8762,"longitude":75.3433,"timezone":"Asia/Kolkata"},
    {"name":"Dhanbad","admin1":"Jharkhand","country":"India","latitude":23.7957,"longitude":86.4304,"timezone":"Asia/Kolkata"},
    {"name":"Amritsar","admin1":"Punjab","country":"India","latitude":31.6340,"longitude":74.8723,"timezone":"Asia/Kolkata"},
    {"name":"Navi Mumbai","admin1":"Maharashtra","country":"India","latitude":19.0330,"longitude":73.0297,"timezone":"Asia/Kolkata"},
    {"name":"Allahabad","admin1":"Uttar Pradesh","country":"India","latitude":25.4358,"longitude":81.8463,"timezone":"Asia/Kolkata"},
    {"name":"Prayagraj","admin1":"Uttar Pradesh","country":"India","latitude":25.4358,"longitude":81.8463,"timezone":"Asia/Kolkata"},
    {"name":"Howrah","admin1":"West Bengal","country":"India","latitude":22.5958,"longitude":88.2636,"timezone":"Asia/Kolkata"},
    {"name":"Ranchi","admin1":"Jharkhand","country":"India","latitude":23.3441,"longitude":85.3096,"timezone":"Asia/Kolkata"},
    {"name":"Gwalior","admin1":"Madhya Pradesh","country":"India","latitude":26.2183,"longitude":78.1828,"timezone":"Asia/Kolkata"},
    {"name":"Jabalpur","admin1":"Madhya Pradesh","country":"India","latitude":23.1815,"longitude":79.9864,"timezone":"Asia/Kolkata"},
    {"name":"Coimbatore","admin1":"Tamil Nadu","country":"India","latitude":11.0168,"longitude":76.9558,"timezone":"Asia/Kolkata"},
    {"name":"Vijayawada","admin1":"Andhra Pradesh","country":"India","latitude":16.5062,"longitude":80.6480,"timezone":"Asia/Kolkata"},
    {"name":"Jodhpur","admin1":"Rajasthan","country":"India","latitude":26.2389,"longitude":73.0243,"timezone":"Asia/Kolkata"},
    {"name":"Madurai","admin1":"Tamil Nadu","country":"India","latitude":9.9252,"longitude":78.1198,"timezone":"Asia/Kolkata"},
    {"name":"Raipur","admin1":"Chhattisgarh","country":"India","latitude":21.2514,"longitude":81.6296,"timezone":"Asia/Kolkata"},
    {"name":"Kota","admin1":"Rajasthan","country":"India","latitude":25.2138,"longitude":75.8648,"timezone":"Asia/Kolkata"},
    {"name":"Guwahati","admin1":"Assam","country":"India","latitude":26.1445,"longitude":91.7362,"timezone":"Asia/Kolkata"},
    {"name":"Chandigarh","admin1":"Chandigarh","country":"India","latitude":30.7333,"longitude":76.7794,"timezone":"Asia/Kolkata"},
    {"name":"Mysore","admin1":"Karnataka","country":"India","latitude":12.2958,"longitude":76.6394,"timezone":"Asia/Kolkata"},
    {"name":"Mysuru","admin1":"Karnataka","country":"India","latitude":12.2958,"longitude":76.6394,"timezone":"Asia/Kolkata"},
    {"name":"Bareilly","admin1":"Uttar Pradesh","country":"India","latitude":28.3670,"longitude":79.4304,"timezone":"Asia/Kolkata"},
    {"name":"Aligarh","admin1":"Uttar Pradesh","country":"India","latitude":27.8974,"longitude":78.0880,"timezone":"Asia/Kolkata"},
    {"name":"Moradabad","admin1":"Uttar Pradesh","country":"India","latitude":28.8386,"longitude":78.7733,"timezone":"Asia/Kolkata"},
    {"name":"Solapur","admin1":"Maharashtra","country":"India","latitude":17.6599,"longitude":75.9064,"timezone":"Asia/Kolkata"},
    {"name":"Hubballi","admin1":"Karnataka","country":"India","latitude":15.3647,"longitude":75.1240,"timezone":"Asia/Kolkata"},
    {"name":"Hubli","admin1":"Karnataka","country":"India","latitude":15.3647,"longitude":75.1240,"timezone":"Asia/Kolkata"},
    {"name":"Tiruchirappalli","admin1":"Tamil Nadu","country":"India","latitude":10.7905,"longitude":78.7047,"timezone":"Asia/Kolkata"},
    {"name":"Trichy","admin1":"Tamil Nadu","country":"India","latitude":10.7905,"longitude":78.7047,"timezone":"Asia/Kolkata"},
    {"name":"Bareilly","admin1":"Uttar Pradesh","country":"India","latitude":28.3670,"longitude":79.4304,"timezone":"Asia/Kolkata"},
    {"name":"Tiruppur","admin1":"Tamil Nadu","country":"India","latitude":11.1085,"longitude":77.3411,"timezone":"Asia/Kolkata"},
    {"name":"Salem","admin1":"Tamil Nadu","country":"India","latitude":11.6643,"longitude":78.1460,"timezone":"Asia/Kolkata"},
    {"name":"Bhiwandi","admin1":"Maharashtra","country":"India","latitude":19.2812,"longitude":73.0483,"timezone":"Asia/Kolkata"},
    {"name":"Saharanpur","admin1":"Uttar Pradesh","country":"India","latitude":29.9680,"longitude":77.5552,"timezone":"Asia/Kolkata"},
    {"name":"Gorakhpur","admin1":"Uttar Pradesh","country":"India","latitude":26.7606,"longitude":83.3732,"timezone":"Asia/Kolkata"},
    {"name":"Bikaner","admin1":"Rajasthan","country":"India","latitude":28.0229,"longitude":73.3119,"timezone":"Asia/Kolkata"},
    {"name":"Amravati","admin1":"Maharashtra","country":"India","latitude":20.9320,"longitude":77.7523,"timezone":"Asia/Kolkata"},
    {"name":"Noida","admin1":"Uttar Pradesh","country":"India","latitude":28.5355,"longitude":77.3910,"timezone":"Asia/Kolkata"},
    {"name":"Jamshedpur","admin1":"Jharkhand","country":"India","latitude":22.8046,"longitude":86.2029,"timezone":"Asia/Kolkata"},
    {"name":"Bhilai","admin1":"Chhattisgarh","country":"India","latitude":21.1938,"longitude":81.3509,"timezone":"Asia/Kolkata"},
    {"name":"Cuttack","admin1":"Odisha","country":"India","latitude":20.4625,"longitude":85.8830,"timezone":"Asia/Kolkata"},
    {"name":"Firozabad","admin1":"Uttar Pradesh","country":"India","latitude":27.1591,"longitude":78.3957,"timezone":"Asia/Kolkata"},
    {"name":"Kochi","admin1":"Kerala","country":"India","latitude":9.9312,"longitude":76.2673,"timezone":"Asia/Kolkata"},
    {"name":"Cochin","admin1":"Kerala","country":"India","latitude":9.9312,"longitude":76.2673,"timezone":"Asia/Kolkata"},
    {"name":"Bhubaneswar","admin1":"Odisha","country":"India","latitude":20.2961,"longitude":85.8245,"timezone":"Asia/Kolkata"},
    {"name":"Warangal","admin1":"Telangana","country":"India","latitude":17.9689,"longitude":79.5941,"timezone":"Asia/Kolkata"},
    {"name":"Mira-Bhayandar","admin1":"Maharashtra","country":"India","latitude":19.2952,"longitude":72.8544,"timezone":"Asia/Kolkata"},
    {"name":"Thiruvananthapuram","admin1":"Kerala","country":"India","latitude":8.5241,"longitude":76.9366,"timezone":"Asia/Kolkata"},
    {"name":"Trivandrum","admin1":"Kerala","country":"India","latitude":8.5241,"longitude":76.9366,"timezone":"Asia/Kolkata"},
    {"name":"Bhiwani","admin1":"Haryana","country":"India","latitude":28.7975,"longitude":76.1322,"timezone":"Asia/Kolkata"},
    {"name":"Saharanpur","admin1":"Uttar Pradesh","country":"India","latitude":29.9680,"longitude":77.5552,"timezone":"Asia/Kolkata"},
    {"name":"Guntur","admin1":"Andhra Pradesh","country":"India","latitude":16.3067,"longitude":80.4365,"timezone":"Asia/Kolkata"},
    {"name":"Bhilwara","admin1":"Rajasthan","country":"India","latitude":25.3463,"longitude":74.6364,"timezone":"Asia/Kolkata"},
    {"name":"Borivali","admin1":"Maharashtra","country":"India","latitude":19.2307,"longitude":72.8567,"timezone":"Asia/Kolkata"},
    {"name":"Amritsar","admin1":"Punjab","country":"India","latitude":31.6340,"longitude":74.8723,"timezone":"Asia/Kolkata"},
    {"name":"Bhavnagar","admin1":"Gujarat","country":"India","latitude":21.7645,"longitude":72.1519,"timezone":"Asia/Kolkata"},
    {"name":"Dehradun","admin1":"Uttarakhand","country":"India","latitude":30.3165,"longitude":78.0322,"timezone":"Asia/Kolkata"},
    {"name":"Durgapur","admin1":"West Bengal","country":"India","latitude":23.5204,"longitude":87.3119,"timezone":"Asia/Kolkata"},
    {"name":"Asansol","admin1":"West Bengal","country":"India","latitude":23.6739,"longitude":86.9524,"timezone":"Asia/Kolkata"},
    {"name":"Rourkela","admin1":"Odisha","country":"India","latitude":22.2604,"longitude":84.8536,"timezone":"Asia/Kolkata"},
    {"name":"Nanded","admin1":"Maharashtra","country":"India","latitude":19.1383,"longitude":77.3210,"timezone":"Asia/Kolkata"},
    {"name":"Kolhapur","admin1":"Maharashtra","country":"India","latitude":16.7050,"longitude":74.2433,"timezone":"Asia/Kolkata"},
    {"name":"Ajmer","admin1":"Rajasthan","country":"India","latitude":26.4499,"longitude":74.6399,"timezone":"Asia/Kolkata"},
    {"name":"Akola","admin1":"Maharashtra","country":"India","latitude":20.7059,"longitude":77.0219,"timezone":"Asia/Kolkata"},
    {"name":"Gulbarga","admin1":"Karnataka","country":"India","latitude":17.3297,"longitude":76.8343,"timezone":"Asia/Kolkata"},
    {"name":"Kalaburagi","admin1":"Karnataka","country":"India","latitude":17.3297,"longitude":76.8343,"timezone":"Asia/Kolkata"},
    {"name":"Jamnagar","admin1":"Gujarat","country":"India","latitude":22.4707,"longitude":70.0577,"timezone":"Asia/Kolkata"},
    {"name":"Ujjain","admin1":"Madhya Pradesh","country":"India","latitude":23.1765,"longitude":75.7885,"timezone":"Asia/Kolkata"},
    {"name":"Loni","admin1":"Uttar Pradesh","country":"India","latitude":28.7515,"longitude":77.2884,"timezone":"Asia/Kolkata"},
    {"name":"Siliguri","admin1":"West Bengal","country":"India","latitude":26.7271,"longitude":88.3953,"timezone":"Asia/Kolkata"},
    {"name":"Jhansi","admin1":"Uttar Pradesh","country":"India","latitude":25.4484,"longitude":78.5685,"timezone":"Asia/Kolkata"},
    {"name":"Ulhasnagar","admin1":"Maharashtra","country":"India","latitude":19.2215,"longitude":73.1645,"timezone":"Asia/Kolkata"},
    {"name":"Jammu","admin1":"Jammu and Kashmir","country":"India","latitude":32.7266,"longitude":74.8570,"timezone":"Asia/Kolkata"},
    {"name":"Sangli","admin1":"Maharashtra","country":"India","latitude":16.8524,"longitude":74.5815,"timezone":"Asia/Kolkata"},
    {"name":"Mangalore","admin1":"Karnataka","country":"India","latitude":12.9141,"longitude":74.8560,"timezone":"Asia/Kolkata"},
    {"name":"Mangaluru","admin1":"Karnataka","country":"India","latitude":12.9141,"longitude":74.8560,"timezone":"Asia/Kolkata"},
    {"name":"Erode","admin1":"Tamil Nadu","country":"India","latitude":11.3410,"longitude":77.7172,"timezone":"Asia/Kolkata"},
    {"name":"Belgaum","admin1":"Karnataka","country":"India","latitude":15.8497,"longitude":74.4977,"timezone":"Asia/Kolkata"},
    {"name":"Belagavi","admin1":"Karnataka","country":"India","latitude":15.8497,"longitude":74.4977,"timezone":"Asia/Kolkata"},
    {"name":"Ambattur","admin1":"Tamil Nadu","country":"India","latitude":13.1143,"longitude":80.1548,"timezone":"Asia/Kolkata"},
    {"name":"Tirunelveli","admin1":"Tamil Nadu","country":"India","latitude":8.7139,"longitude":77.7567,"timezone":"Asia/Kolkata"},
    {"name":"Malegaon","admin1":"Maharashtra","country":"India","latitude":20.5579,"longitude":74.5089,"timezone":"Asia/Kolkata"},
    {"name":"Gaya","admin1":"Bihar","country":"India","latitude":24.7914,"longitude":85.0002,"timezone":"Asia/Kolkata"},
    {"name":"Jalgaon","admin1":"Maharashtra","country":"India","latitude":21.0077,"longitude":75.5626,"timezone":"Asia/Kolkata"},
    {"name":"Udaipur","admin1":"Rajasthan","country":"India","latitude":24.5854,"longitude":73.7125,"timezone":"Asia/Kolkata"},
    {"name":"Maheshtala","admin1":"West Bengal","country":"India","latitude":22.5018,"longitude":88.2487,"timezone":"Asia/Kolkata"},
    {"name":"Tirupur","admin1":"Tamil Nadu","country":"India","latitude":11.1085,"longitude":77.3411,"timezone":"Asia/Kolkata"},
    {"name":"Davangere","admin1":"Karnataka","country":"India","latitude":14.4644,"longitude":75.9218,"timezone":"Asia/Kolkata"},
    {"name":"Kozhikode","admin1":"Kerala","country":"India","latitude":11.2588,"longitude":75.7804,"timezone":"Asia/Kolkata"},
    {"name":"Calicut","admin1":"Kerala","country":"India","latitude":11.2588,"longitude":75.7804,"timezone":"Asia/Kolkata"},
    {"name":"Akbarpur","admin1":"Uttar Pradesh","country":"India","latitude":26.4308,"longitude":82.5374,"timezone":"Asia/Kolkata"},
    {"name":"Kurnool","admin1":"Andhra Pradesh","country":"India","latitude":15.8281,"longitude":78.0373,"timezone":"Asia/Kolkata"},
    {"name":"Bokaro","admin1":"Jharkhand","country":"India","latitude":23.6693,"longitude":86.1511,"timezone":"Asia/Kolkata"},
    {"name":"Rajahmundry","admin1":"Andhra Pradesh","country":"India","latitude":17.0005,"longitude":81.8040,"timezone":"Asia/Kolkata"},
    {"name":"Ballari","admin1":"Karnataka","country":"India","latitude":15.1394,"longitude":76.9214,"timezone":"Asia/Kolkata"},
    {"name":"Bellary","admin1":"Karnataka","country":"India","latitude":15.1394,"longitude":76.9214,"timezone":"Asia/Kolkata"},
    {"name":"Agartala","admin1":"Tripura","country":"India","latitude":23.8315,"longitude":91.2868,"timezone":"Asia/Kolkata"},
    {"name":"Bhagalpur","admin1":"Bihar","country":"India","latitude":25.2425,"longitude":86.9842,"timezone":"Asia/Kolkata"},
    {"name":"Latur","admin1":"Maharashtra","country":"India","latitude":18.4088,"longitude":76.5604,"timezone":"Asia/Kolkata"},
    {"name":"Dhule","admin1":"Maharashtra","country":"India","latitude":20.9042,"longitude":74.7749,"timezone":"Asia/Kolkata"},
    {"name":"Korba","admin1":"Chhattisgarh","country":"India","latitude":22.3595,"longitude":82.7501,"timezone":"Asia/Kolkata"},
    {"name":"Bhilai Nagar","admin1":"Chhattisgarh","country":"India","latitude":21.1938,"longitude":81.3509,"timezone":"Asia/Kolkata"},
    {"name":"Berhampur","admin1":"Odisha","country":"India","latitude":19.3149,"longitude":84.7941,"timezone":"Asia/Kolkata"},
    {"name":"Muzaffarpur","admin1":"Bihar","country":"India","latitude":26.1209,"longitude":85.3647,"timezone":"Asia/Kolkata"},
    {"name":"Ahmednagar","admin1":"Maharashtra","country":"India","latitude":19.0948,"longitude":74.7480,"timezone":"Asia/Kolkata"},
    {"name":"Mathura","admin1":"Uttar Pradesh","country":"India","latitude":27.4924,"longitude":77.6737,"timezone":"Asia/Kolkata"},
    {"name":"Kollam","admin1":"Kerala","country":"India","latitude":8.8932,"longitude":76.6141,"timezone":"Asia/Kolkata"},
    {"name":"Avadi","admin1":"Tamil Nadu","country":"India","latitude":13.1147,"longitude":80.1098,"timezone":"Asia/Kolkata"},
    {"name":"Kadapa","admin1":"Andhra Pradesh","country":"India","latitude":14.4673,"longitude":78.8242,"timezone":"Asia/Kolkata"},
    {"name":"Kamarhati","admin1":"West Bengal","country":"India","latitude":22.6700,"longitude":88.3725,"timezone":"Asia/Kolkata"},
    {"name":"Sambalpur","admin1":"Odisha","country":"India","latitude":21.4669,"longitude":83.9756,"timezone":"Asia/Kolkata"},
    {"name":"Bilaspur","admin1":"Chhattisgarh","country":"India","latitude":22.0797,"longitude":82.1409,"timezone":"Asia/Kolkata"},
    {"name":"Shahjahanpur","admin1":"Uttar Pradesh","country":"India","latitude":27.8814,"longitude":79.9098,"timezone":"Asia/Kolkata"},
    {"name":"Satara","admin1":"Maharashtra","country":"India","latitude":17.6805,"longitude":74.0183,"timezone":"Asia/Kolkata"},
    {"name":"Bijapur","admin1":"Karnataka","country":"India","latitude":16.8302,"longitude":75.7100,"timezone":"Asia/Kolkata"},
    {"name":"Vijayapura","admin1":"Karnataka","country":"India","latitude":16.8302,"longitude":75.7100,"timezone":"Asia/Kolkata"},
    {"name":"Rampur","admin1":"Uttar Pradesh","country":"India","latitude":28.8152,"longitude":79.0220,"timezone":"Asia/Kolkata"},
    {"name":"Shimoga","admin1":"Karnataka","country":"India","latitude":13.9299,"longitude":75.5681,"timezone":"Asia/Kolkata"},
    {"name":"Shivamogga","admin1":"Karnataka","country":"India","latitude":13.9299,"longitude":75.5681,"timezone":"Asia/Kolkata"},
    {"name":"Chandrapur","admin1":"Maharashtra","country":"India","latitude":19.9615,"longitude":79.2961,"timezone":"Asia/Kolkata"},
    {"name":"Junagadh","admin1":"Gujarat","country":"India","latitude":21.5222,"longitude":70.4579,"timezone":"Asia/Kolkata"},
    {"name":"Thrissur","admin1":"Kerala","country":"India","latitude":10.5276,"longitude":76.2144,"timezone":"Asia/Kolkata"},
    {"name":"Trichur","admin1":"Kerala","country":"India","latitude":10.5276,"longitude":76.2144,"timezone":"Asia/Kolkata"},
    {"name":"Alwar","admin1":"Rajasthan","country":"India","latitude":27.5530,"longitude":76.6346,"timezone":"Asia/Kolkata"},
    {"name":"Bardhaman","admin1":"West Bengal","country":"India","latitude":23.2324,"longitude":87.8615,"timezone":"Asia/Kolkata"},
    {"name":"Kulti","admin1":"West Bengal","country":"India","latitude":23.7300,"longitude":86.8400,"timezone":"Asia/Kolkata"},
    {"name":"Kakinada","admin1":"Andhra Pradesh","country":"India","latitude":16.9891,"longitude":82.2475,"timezone":"Asia/Kolkata"},
    {"name":"Nizamabad","admin1":"Telangana","country":"India","latitude":18.6725,"longitude":78.0941,"timezone":"Asia/Kolkata"},
    {"name":"Parbhani","admin1":"Maharashtra","country":"India","latitude":19.2608,"longitude":76.7707,"timezone":"Asia/Kolkata"},
    {"name":"Tumkur","admin1":"Karnataka","country":"India","latitude":13.3409,"longitude":77.1011,"timezone":"Asia/Kolkata"},
    {"name":"Tumakuru","admin1":"Karnataka","country":"India","latitude":13.3409,"longitude":77.1011,"timezone":"Asia/Kolkata"},
    {"name":"Hisar","admin1":"Haryana","country":"India","latitude":29.1492,"longitude":75.7217,"timezone":"Asia/Kolkata"},
    {"name":"Ozhukarai","admin1":"Puducherry","country":"India","latitude":11.9469,"longitude":79.7913,"timezone":"Asia/Kolkata"},
    {"name":"Bihar Sharif","admin1":"Bihar","country":"India","latitude":25.1968,"longitude":85.5147,"timezone":"Asia/Kolkata"},
    {"name":"Panipat","admin1":"Haryana","country":"India","latitude":29.3909,"longitude":76.9635,"timezone":"Asia/Kolkata"},
    {"name":"Darbhanga","admin1":"Bihar","country":"India","latitude":26.1542,"longitude":85.8918,"timezone":"Asia/Kolkata"},
    {"name":"Bally","admin1":"West Bengal","country":"India","latitude":22.6492,"longitude":88.3401,"timezone":"Asia/Kolkata"},
    {"name":"Aizawl","admin1":"Mizoram","country":"India","latitude":23.7271,"longitude":92.7176,"timezone":"Asia/Kolkata"},
    {"name":"Dewas","admin1":"Madhya Pradesh","country":"India","latitude":22.9676,"longitude":76.0534,"timezone":"Asia/Kolkata"},
    {"name":"Ichalkaranji","admin1":"Maharashtra","country":"India","latitude":16.6914,"longitude":74.4607,"timezone":"Asia/Kolkata"},
    {"name":"Karnal","admin1":"Haryana","country":"India","latitude":29.6857,"longitude":76.9905,"timezone":"Asia/Kolkata"},
    {"name":"Bathinda","admin1":"Punjab","country":"India","latitude":30.2110,"longitude":74.9455,"timezone":"Asia/Kolkata"},
    {"name":"Jalna","admin1":"Maharashtra","country":"India","latitude":19.8410,"longitude":75.8864,"timezone":"Asia/Kolkata"},
    {"name":"Eluru","admin1":"Andhra Pradesh","country":"India","latitude":16.7107,"longitude":81.0952,"timezone":"Asia/Kolkata"},
    {"name":"Kirari Suleman Nagar","admin1":"Delhi","country":"India","latitude":28.7370,"longitude":77.0744,"timezone":"Asia/Kolkata"},
    {"name":"Barasat","admin1":"West Bengal","country":"India","latitude":22.7245,"longitude":88.4807,"timezone":"Asia/Kolkata"},
    {"name":"Purnia","admin1":"Bihar","country":"India","latitude":25.7771,"longitude":87.4753,"timezone":"Asia/Kolkata"},
    {"name":"Satna","admin1":"Madhya Pradesh","country":"India","latitude":24.5828,"longitude":80.8261,"timezone":"Asia/Kolkata"},
    {"name":"Mau","admin1":"Uttar Pradesh","country":"India","latitude":25.9417,"longitude":83.5611,"timezone":"Asia/Kolkata"},
    {"name":"Sonipat","admin1":"Haryana","country":"India","latitude":28.9931,"longitude":77.0151,"timezone":"Asia/Kolkata"},
    {"name":"Farrukhabad","admin1":"Uttar Pradesh","country":"India","latitude":27.3929,"longitude":79.5805,"timezone":"Asia/Kolkata"},
    {"name":"Sagar","admin1":"Madhya Pradesh","country":"India","latitude":23.8388,"longitude":78.7378,"timezone":"Asia/Kolkata"},
    {"name":"Durg","admin1":"Chhattisgarh","country":"India","latitude":21.1903,"longitude":81.2849,"timezone":"Asia/Kolkata"},
    {"name":"Imphal","admin1":"Manipur","country":"India","latitude":24.8170,"longitude":93.9368,"timezone":"Asia/Kolkata"},
    {"name":"Ratlam","admin1":"Madhya Pradesh","country":"India","latitude":23.3315,"longitude":75.0367,"timezone":"Asia/Kolkata"},
    {"name":"Hapur","admin1":"Uttar Pradesh","country":"India","latitude":28.7306,"longitude":77.7758,"timezone":"Asia/Kolkata"},
    {"name":"Arrah","admin1":"Bihar","country":"India","latitude":25.5541,"longitude":84.6630,"timezone":"Asia/Kolkata"},
    {"name":"Anantapur","admin1":"Andhra Pradesh","country":"India","latitude":14.6819,"longitude":77.6006,"timezone":"Asia/Kolkata"},
    {"name":"Karimnagar","admin1":"Telangana","country":"India","latitude":18.4386,"longitude":79.1288,"timezone":"Asia/Kolkata"},
    {"name":"Etawah","admin1":"Uttar Pradesh","country":"India","latitude":26.7855,"longitude":79.0150,"timezone":"Asia/Kolkata"},
    {"name":"Ambernath","admin1":"Maharashtra","country":"India","latitude":19.1879,"longitude":73.1505,"timezone":"Asia/Kolkata"},
    {"name":"North Dumdum","admin1":"West Bengal","country":"India","latitude":22.6442,"longitude":88.4072,"timezone":"Asia/Kolkata"},
    {"name":"Bharatpur","admin1":"Rajasthan","country":"India","latitude":27.2152,"longitude":77.4977,"timezone":"Asia/Kolkata"},
    {"name":"Begusarai","admin1":"Bihar","country":"India","latitude":25.4182,"longitude":86.1272,"timezone":"Asia/Kolkata"},
    {"name":"New Delhi","admin1":"Delhi","country":"India","latitude":28.6139,"longitude":77.2090,"timezone":"Asia/Kolkata"},
    {"name":"Gandhidham","admin1":"Gujarat","country":"India","latitude":23.0753,"longitude":70.1337,"timezone":"Asia/Kolkata"},
    {"name":"Baranagar","admin1":"West Bengal","country":"India","latitude":22.6427,"longitude":88.3722,"timezone":"Asia/Kolkata"},
    {"name":"Tiruvottiyur","admin1":"Tamil Nadu","country":"India","latitude":13.1645,"longitude":80.3019,"timezone":"Asia/Kolkata"},
    {"name":"Puducherry","admin1":"Puducherry","country":"India","latitude":11.9416,"longitude":79.8083,"timezone":"Asia/Kolkata"},
    {"name":"Pondicherry","admin1":"Puducherry","country":"India","latitude":11.9416,"longitude":79.8083,"timezone":"Asia/Kolkata"},
    {"name":"Sikar","admin1":"Rajasthan","country":"India","latitude":27.6094,"longitude":75.1399,"timezone":"Asia/Kolkata"},
    {"name":"Thoothukudi","admin1":"Tamil Nadu","country":"India","latitude":8.7642,"longitude":78.1348,"timezone":"Asia/Kolkata"},
    {"name":"Tuticorin","admin1":"Tamil Nadu","country":"India","latitude":8.7642,"longitude":78.1348,"timezone":"Asia/Kolkata"},
    {"name":"Rewa","admin1":"Madhya Pradesh","country":"India","latitude":24.5364,"longitude":81.3027,"timezone":"Asia/Kolkata"},
    {"name":"Mirzapur","admin1":"Uttar Pradesh","country":"India","latitude":25.1463,"longitude":82.5650,"timezone":"Asia/Kolkata"},
    {"name":"Raichur","admin1":"Karnataka","country":"India","latitude":16.2076,"longitude":77.3463,"timezone":"Asia/Kolkata"},
    {"name":"Pali","admin1":"Rajasthan","country":"India","latitude":25.7711,"longitude":73.3234,"timezone":"Asia/Kolkata"},
    {"name":"Ramagundam","admin1":"Telangana","country":"India","latitude":18.7536,"longitude":79.4738,"timezone":"Asia/Kolkata"},
    {"name":"Silchar","admin1":"Assam","country":"India","latitude":24.8333,"longitude":92.7789,"timezone":"Asia/Kolkata"},
    {"name":"Haridwar","admin1":"Uttarakhand","country":"India","latitude":29.9457,"longitude":78.1642,"timezone":"Asia/Kolkata"},
    {"name":"Vijayanagaram","admin1":"Andhra Pradesh","country":"India","latitude":18.1067,"longitude":83.3956,"timezone":"Asia/Kolkata"},
    {"name":"Tenali","admin1":"Andhra Pradesh","country":"India","latitude":16.2380,"longitude":80.6406,"timezone":"Asia/Kolkata"},
    {"name":"Nagercoil","admin1":"Tamil Nadu","country":"India","latitude":8.1779,"longitude":77.4339,"timezone":"Asia/Kolkata"},
    {"name":"Sri Ganganagar","admin1":"Rajasthan","country":"India","latitude":29.9094,"longitude":73.8800,"timezone":"Asia/Kolkata"},
    {"name":"Karawal Nagar","admin1":"Delhi","country":"India","latitude":28.7320,"longitude":77.2740,"timezone":"Asia/Kolkata"},
    {"name":"Karaikudi","admin1":"Tamil Nadu","country":"India","latitude":10.0671,"longitude":78.7791,"timezone":"Asia/Kolkata"},
    {"name":"Bhusawal","admin1":"Maharashtra","country":"India","latitude":21.0444,"longitude":75.7849,"timezone":"Asia/Kolkata"},
    {"name":"Hindupur","admin1":"Andhra Pradesh","country":"India","latitude":13.8290,"longitude":77.4924,"timezone":"Asia/Kolkata"},
    {"name":"Nadiad","admin1":"Gujarat","country":"India","latitude":22.6939,"longitude":72.8634,"timezone":"Asia/Kolkata"},
    {"name":"Machilipatnam","admin1":"Andhra Pradesh","country":"India","latitude":16.1875,"longitude":81.1389,"timezone":"Asia/Kolkata"},
    {"name":"Adoni","admin1":"Andhra Pradesh","country":"India","latitude":15.6322,"longitude":77.2750,"timezone":"Asia/Kolkata"},
    {"name":"Yamunanagar","admin1":"Haryana","country":"India","latitude":30.1290,"longitude":77.2674,"timezone":"Asia/Kolkata"},
    {"name":"Bhimavaram","admin1":"Andhra Pradesh","country":"India","latitude":16.5449,"longitude":81.5212,"timezone":"Asia/Kolkata"},
    {"name":"Kumbakonam","admin1":"Tamil Nadu","country":"India","latitude":10.9595,"longitude":79.3845,"timezone":"Asia/Kolkata"},
    {"name":"Tirupati","admin1":"Andhra Pradesh","country":"India","latitude":13.6288,"longitude":79.4192,"timezone":"Asia/Kolkata"},
    {"name":"Hosur","admin1":"Tamil Nadu","country":"India","latitude":12.7409,"longitude":77.8253,"timezone":"Asia/Kolkata"},
    {"name":"Vellore","admin1":"Tamil Nadu","country":"India","latitude":12.9165,"longitude":79.1325,"timezone":"Asia/Kolkata"},
    {"name":"Bidar","admin1":"Karnataka","country":"India","latitude":17.9133,"longitude":77.5301,"timezone":"Asia/Kolkata"},
    {"name":"Bhuj","admin1":"Gujarat","country":"India","latitude":23.2419,"longitude":69.6669,"timezone":"Asia/Kolkata"},
    {"name":"Khammam","admin1":"Telangana","country":"India","latitude":17.2473,"longitude":80.1514,"timezone":"Asia/Kolkata"},
    {"name":"Burhanpur","admin1":"Madhya Pradesh","country":"India","latitude":21.3074,"longitude":76.2293,"timezone":"Asia/Kolkata"},
    {"name":"Karur","admin1":"Tamil Nadu","country":"India","latitude":10.9601,"longitude":78.0766,"timezone":"Asia/Kolkata"},
    {"name":"Hajipur","admin1":"Bihar","country":"India","latitude":25.6841,"longitude":85.2080,"timezone":"Asia/Kolkata"},
    {"name":"Mahbubnagar","admin1":"Telangana","country":"India","latitude":16.7480,"longitude":77.9961,"timezone":"Asia/Kolkata"},
    {"name":"Aurangabad","admin1":"Bihar","country":"India","latitude":24.7522,"longitude":84.3742,"timezone":"Asia/Kolkata"},
    {"name":"Saharsa","admin1":"Bihar","country":"India","latitude":25.8804,"longitude":86.5907,"timezone":"Asia/Kolkata"},
    {"name":"Hazaribagh","admin1":"Jharkhand","country":"India","latitude":23.9925,"longitude":85.3637,"timezone":"Asia/Kolkata"},
    {"name":"Cuddalore","admin1":"Tamil Nadu","country":"India","latitude":11.7480,"longitude":79.7714,"timezone":"Asia/Kolkata"},
    {"name":"Anand","admin1":"Gujarat","country":"India","latitude":22.5645,"longitude":72.9289,"timezone":"Asia/Kolkata"},
    {"name":"Vidisha","admin1":"Madhya Pradesh","country":"India","latitude":23.5236,"longitude":77.8140,"timezone":"Asia/Kolkata"},
    {"name":"Bettiah","admin1":"Bihar","country":"India","latitude":26.8023,"longitude":84.5031,"timezone":"Asia/Kolkata"},
    {"name":"Sitamarhi","admin1":"Bihar","country":"India","latitude":26.5897,"longitude":85.4929,"timezone":"Asia/Kolkata"},
    {"name":"Chapra","admin1":"Bihar","country":"India","latitude":25.7793,"longitude":84.7278,"timezone":"Asia/Kolkata"},
    {"name":"Sasaram","admin1":"Bihar","country":"India","latitude":24.9525,"longitude":84.0186,"timezone":"Asia/Kolkata"},
    {"name":"Munger","admin1":"Bihar","country":"India","latitude":25.3760,"longitude":86.4734,"timezone":"Asia/Kolkata"},
    {"name":"Bhilwara","admin1":"Rajasthan","country":"India","latitude":25.3463,"longitude":74.6364,"timezone":"Asia/Kolkata"},
    {"name":"Bhusawal","admin1":"Maharashtra","country":"India","latitude":21.0444,"longitude":75.7849,"timezone":"Asia/Kolkata"},
    {"name":"Panvel","admin1":"Maharashtra","country":"India","latitude":18.9894,"longitude":73.1175,"timezone":"Asia/Kolkata"},
    {"name":"Vasai","admin1":"Maharashtra","country":"India","latitude":19.4258,"longitude":72.8230,"timezone":"Asia/Kolkata"},
    {"name":"Virar","admin1":"Maharashtra","country":"India","latitude":19.4559,"longitude":72.8113,"timezone":"Asia/Kolkata"},
    {"name":"Dombivli","admin1":"Maharashtra","country":"India","latitude":19.2183,"longitude":73.0860,"timezone":"Asia/Kolkata"},
    {"name":"Khurda","admin1":"Odisha","country":"India","latitude":20.1818,"longitude":85.6147,"timezone":"Asia/Kolkata"},
    {"name":"Puri","admin1":"Odisha","country":"India","latitude":19.8135,"longitude":85.8312,"timezone":"Asia/Kolkata"},
    {"name":"Rishikesh","admin1":"Uttarakhand","country":"India","latitude":30.0869,"longitude":78.2676,"timezone":"Asia/Kolkata"},
    {"name":"Nainital","admin1":"Uttarakhand","country":"India","latitude":29.3919,"longitude":79.4542,"timezone":"Asia/Kolkata"},
    {"name":"Roorkee","admin1":"Uttarakhand","country":"India","latitude":29.8543,"longitude":77.8880,"timezone":"Asia/Kolkata"},
    {"name":"Mussoorie","admin1":"Uttarakhand","country":"India","latitude":30.4598,"longitude":78.0644,"timezone":"Asia/Kolkata"},
    {"name":"Shimla","admin1":"Himachal Pradesh","country":"India","latitude":31.1048,"longitude":77.1734,"timezone":"Asia/Kolkata"},
    {"name":"Manali","admin1":"Himachal Pradesh","country":"India","latitude":32.2432,"longitude":77.1892,"timezone":"Asia/Kolkata"},
    {"name":"Dharamshala","admin1":"Himachal Pradesh","country":"India","latitude":32.2190,"longitude":76.3234,"timezone":"Asia/Kolkata"},
    {"name":"Solan","admin1":"Himachal Pradesh","country":"India","latitude":30.9080,"longitude":77.0996,"timezone":"Asia/Kolkata"},
    {"name":"Mandi","admin1":"Himachal Pradesh","country":"India","latitude":31.7080,"longitude":76.9320,"timezone":"Asia/Kolkata"},
    {"name":"Leh","admin1":"Ladakh","country":"India","latitude":34.1526,"longitude":77.5770,"timezone":"Asia/Kolkata"},
    {"name":"Kargil","admin1":"Ladakh","country":"India","latitude":34.5539,"longitude":76.1349,"timezone":"Asia/Kolkata"},
    {"name":"Anantnag","admin1":"Jammu and Kashmir","country":"India","latitude":33.7333,"longitude":75.1500,"timezone":"Asia/Kolkata"},
    {"name":"Baramulla","admin1":"Jammu and Kashmir","country":"India","latitude":34.2095,"longitude":74.3429,"timezone":"Asia/Kolkata"},
    {"name":"Udhampur","admin1":"Jammu and Kashmir","country":"India","latitude":32.9239,"longitude":75.1416,"timezone":"Asia/Kolkata"},
    {"name":"Kathua","admin1":"Jammu and Kashmir","country":"India","latitude":32.3854,"longitude":75.5179,"timezone":"Asia/Kolkata"},
    {"name":"Vrindavan","admin1":"Uttar Pradesh","country":"India","latitude":27.5806,"longitude":77.7006,"timezone":"Asia/Kolkata"},
    {"name":"Ayodhya","admin1":"Uttar Pradesh","country":"India","latitude":26.7922,"longitude":82.1998,"timezone":"Asia/Kolkata"},
    {"name":"Sultanpur","admin1":"Uttar Pradesh","country":"India","latitude":26.2658,"longitude":82.0727,"timezone":"Asia/Kolkata"},
    {"name":"Faizabad","admin1":"Uttar Pradesh","country":"India","latitude":26.7733,"longitude":82.1456,"timezone":"Asia/Kolkata"},
    {"name":"Basti","admin1":"Uttar Pradesh","country":"India","latitude":26.8141,"longitude":82.7370,"timezone":"Asia/Kolkata"},
    {"name":"Deoria","admin1":"Uttar Pradesh","country":"India","latitude":26.5025,"longitude":83.7791,"timezone":"Asia/Kolkata"},
    {"name":"Azamgarh","admin1":"Uttar Pradesh","country":"India","latitude":26.0683,"longitude":83.1836,"timezone":"Asia/Kolkata"},
    {"name":"Jaunpur","admin1":"Uttar Pradesh","country":"India","latitude":25.7470,"longitude":82.6837,"timezone":"Asia/Kolkata"},
    {"name":"Ballia","admin1":"Uttar Pradesh","country":"India","latitude":25.7615,"longitude":84.1497,"timezone":"Asia/Kolkata"},
    {"name":"Pratapgarh","admin1":"Uttar Pradesh","country":"India","latitude":25.8954,"longitude":81.9438,"timezone":"Asia/Kolkata"},
    {"name":"Raebareli","admin1":"Uttar Pradesh","country":"India","latitude":26.2152,"longitude":81.2333,"timezone":"Asia/Kolkata"},
    {"name":"Sitapur","admin1":"Uttar Pradesh","country":"India","latitude":27.5615,"longitude":80.6890,"timezone":"Asia/Kolkata"},
    {"name":"Hardoi","admin1":"Uttar Pradesh","country":"India","latitude":27.4156,"longitude":80.1318,"timezone":"Asia/Kolkata"},
    {"name":"Unnao","admin1":"Uttar Pradesh","country":"India","latitude":26.5466,"longitude":80.4879,"timezone":"Asia/Kolkata"},
    {"name":"Lakhimpur","admin1":"Uttar Pradesh","country":"India","latitude":27.9505,"longitude":80.7841,"timezone":"Asia/Kolkata"},
    {"name":"Bahraich","admin1":"Uttar Pradesh","country":"India","latitude":27.5743,"longitude":81.5946,"timezone":"Asia/Kolkata"},
    {"name":"Gonda","admin1":"Uttar Pradesh","country":"India","latitude":27.1306,"longitude":81.9627,"timezone":"Asia/Kolkata"},
    {"name":"Shahjahanpur","admin1":"Uttar Pradesh","country":"India","latitude":27.8814,"longitude":79.9098,"timezone":"Asia/Kolkata"},
    {"name":"Kanpur Dehat","admin1":"Uttar Pradesh","country":"India","latitude":26.4136,"longitude":79.9806,"timezone":"Asia/Kolkata"},
    {"name":"Banda","admin1":"Uttar Pradesh","country":"India","latitude":25.4761,"longitude":80.3349,"timezone":"Asia/Kolkata"},
    {"name":"Chitrakoot","admin1":"Uttar Pradesh","country":"India","latitude":25.2000,"longitude":80.9000,"timezone":"Asia/Kolkata"},
    {"name":"Hamirpur","admin1":"Uttar Pradesh","country":"India","latitude":25.9560,"longitude":80.1488,"timezone":"Asia/Kolkata"},
    {"name":"Mahoba","admin1":"Uttar Pradesh","country":"India","latitude":25.2918,"longitude":79.8728,"timezone":"Asia/Kolkata"},
    {"name":"Lalitpur","admin1":"Uttar Pradesh","country":"India","latitude":24.6877,"longitude":78.4144,"timezone":"Asia/Kolkata"},
    {"name":"Mainpuri","admin1":"Uttar Pradesh","country":"India","latitude":27.2353,"longitude":79.0270,"timezone":"Asia/Kolkata"},
    {"name":"Etah","admin1":"Uttar Pradesh","country":"India","latitude":27.5605,"longitude":78.6628,"timezone":"Asia/Kolkata"},
    {"name":"Kasganj","admin1":"Uttar Pradesh","country":"India","latitude":27.8083,"longitude":78.6453,"timezone":"Asia/Kolkata"},
    {"name":"Budaun","admin1":"Uttar Pradesh","country":"India","latitude":28.0387,"longitude":79.1259,"timezone":"Asia/Kolkata"},
    {"name":"Pilibhit","admin1":"Uttar Pradesh","country":"India","latitude":28.6306,"longitude":79.8043,"timezone":"Asia/Kolkata"}
  ]
}
